[package]
name = "gen_callgraph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lsp-types = "0.95.1"
serde_json = "1.0.114"
serde = "1.0.197"
tokio = {version = "1.36.0", features = ["full"]}
